### ISSUE TITLE
I get a 0 instead of 0.87 in my parsing of a Real number.

### ISSUE THREAD

**Issue by Danielgb23** [mcmtroffaes/inipp#12]
In this project:
https://github.com/Danielgb23/EA872-projeto
If I configure the config/player.ini attack_rate to 0.87 for example the parser reads it as a 0 which leads to a division by zero later on in the code.

It's read in this line of the code:
		attack_rate = reader.GetReal("stats", "attack_rate", -1);
At the line 49 of src/model/entity.cpp. I checked it out with GDB and it really reads it  as zero. If I change to other number it reads it normally. Real numbers like 4.3 are read normally (actually they change to 4.299999 or something like that).

My machine is 20.04 Ubuntu

**Comment by Danielgb23** [comment]
The variables receiving the data were set as int not float. Solved

**Comment by mcmtroffaes** [comment]
Glad to hear you figured out the problem!
