### ISSUE TITLE
Compile error with C++17, ptr_fun deprecated

### ISSUE THREAD

**Issue by jbfuehrer** [mcmtroffaes/inipp#2]
Hey,

the ltrim/rtrim implementations generate compile errors for me with C++17 as a language standard because std::ptr_fun is deprecated since C++11 and finaly removed in 17. Do you mind changing this to a lambda, i.e. the full implementation of ltrim would then become:

`template <class CharT>
inline void ltrim(std::basic_string<CharT> & s) {
    s.erase(s.begin(), std::find_if(s.begin(), s.end(),
    [](int c) {return !std::isspace(c); }));
}`

I can also do a PR if you like.

**Comment by mcmtroffaes** [comment]
I've fixed it on develop as per the advice at https://stackoverflow.com/a/217605 - thanks for reporting!
