### ISSUE TITLE
[Feature request] Add CMake support

### ISSUE THREAD

**Issue by higaski** [mcmtroffaes/inipp#20]
Maybe someone would be willing to add proper CMake support which means to at least define an INTERFACE library as target.

**Comment by mcmtroffaes** [comment]
As a header only library, why would someone be interested in having an INTERFACE library target? I mean this as an honest question, out of curiosity, as I'm not extremely familiar with cmake.

If there's a good reason, any guidance you could give about how to handle a header-only library like inipp would be great!

**Comment by higaski** [comment]
I've tried to pull inipp into my own CMake project using CMakes [FetchContent module](https://cmake.org/cmake/help/latest/module/FetchContent.html). This means you can practically copy/paste a github URL and you're good to go. Currently this doesn't work and I guess the reason why is because the file in the root directory doesn't specify any targets one could link against.

And to answer your question why someone would every need an INTERFACE target... Have you heard of the small C++ library "Boost". :smile:
I think like 95 out of 100 of their targets or so are of type INTERFACE.

I'm not a CMake guru myself (and looking at 80% of the CMake out there I'd say hardly anybody is) but I think I could at least improve on the current state of affairs. If you want I would create a PR with some improvements.

**Comment by mcmtroffaes** [comment]
I hear you, I've written plenty of cmake code, but still rely on more knowledgeable folks to review (and often correct) my code. 😄  If you know what to do to make it work with FetchContent, please by all means, I'd very much welcome a PR.

**Comment by higaski** [comment]
See PR #21
