### ISSUE TITLE
How to set a value

### ISSUE THREAD

**Issue by Ma5t3rful** [mcmtroffaes/inipp#24]
How to set a value?
something like `inipp::get_value();` but to set a value would be great
Thanks.

**Comment by mcmtroffaes** [comment]
```
ini.sections["section_name"]["variable_name"] = "value"
```

Does this help?

**Comment by Ma5t3rful** [comment]
Hello thank you for answering my question. It does help but i need more info:

## Reading with this method:
in `ArduinoJson` which is a cross-platform JSON parser library. you can do somthing like this.
`int a = JsonDoc["a"]["val"];`
and it can auto-magically convert the number values in JSON string to `int`. (you can also tell it explicitly)
now how about this library? 
can i use the following code?
`int a = ini.sections["section_name"]["variable_name"]; // in ini file it is equal to "65"`

## Writing with this method
can it auto-convert for writing a value?
`ini.sections["section_name"]["variable_name"] = 65;`
does this code turns 65 into an `A` character (ASCII value of 'A') or `"65"` in the output?

**Comment by mcmtroffaes** [comment]
Everything is stored as a string. So...

> can i use the following code?
> `int a = ini.sections["section_name"]["variable_name"]; // in ini file it is equal to "65"`

That won't work. Use the get_value helper method to convert from strings to other types. This will handle any conversion errors appropriately.

> ## Writing with this method
> can it auto-convert for writing a value?
> `ini.sections["section_name"]["variable_name"] = 65;` does this code turns 65 into an `A` character (ASCII value of 'A') or `"65"` in the output.

That won't work either. Use the appropriate string conversion method for the type you want to store.

**Comment by Ma5t3rful** [comment]
OK. Thank you for helping me. I appreciate your kind work.

**Comment by mcmtroffaes** [comment]
Glad I could help. Good luck with your coding!
