### ISSUE TITLE
Writing comments

### ISSUE THREAD

**Issue by droscoe** [mcmtroffaes/inipp#26]
I came across this project and like its compactness.  I was wondering... for the generation feature, is it possible to generate comments?  I couldn't see an easy way to do it without modification.  I see it ignores them on parsing, but not that it can write them.

Thanks!

**Comment by droscoe** [comment]
I wanted to follow-up... since I have to open an fstream anyway, I can write them to the file manually.  Then use this to change/update just the sections and variables.  Thank you for this tidy little application.

**Comment by mcmtroffaes** [comment]
For generating trailing comments at variables you can just append them to the value before generating. Does that help?

**Comment by droscoe** [comment]
> For generating trailing comments at variables you can just append them to the value before generating. Does that help?

Not really, I want to put comment blocks before each section explaining the values contained in the section and their ranges, etc

**Comment by mcmtroffaes** [comment]
The best I can think of is to treat the comments as part of the ini data, for instance by having a section called ``[<section>-comments]`` where you assign comments to dummy variables. However this is a bit controverted, and the result may not suit every purpose.

The spirit of the header is towards simplicity, so beyond trailing comments, as these can be treated quite simply as part of the value, the header steers away from enhancing the data structure to store and write comments in more complex manners... I'm sorry I can't be more helpful!
