### ISSUE TITLE
[bug] Skips fist line 

### ISSUE THREAD

**Issue by Corgile** [mcmtroffaes/inipp#31]
if first line of ini is `[section one]`, then section one is skipped, and `ini.generate(std::cout)` will print out an empty named section like `[]` ("section one" is missed.)

please fix

**Comment by mcmtroffaes** [comment]
Thanks for taking the time to report this. However, I can't reproduce. See https://ci.appveyor.com/project/mcmtroffaes/inipp/builds/50664711

**Comment by Corgile** [comment]
> Thanks for taking the time to report this. However, I can't reproduce. See https://ci.appveyor.com/project/mcmtroffaes/inipp/builds/50664711

sorry, I can't reproduce it either. I just meet this problem for only once, so I'm closing this issue

sorry again for misinforming and time wasting.

**Comment by Corgile** [comment]
misinformation
